Repository DIDIM-ai/frontend, pull requests merged in 2025-07, with the labels that each got.

#31 사용자 예외 처리 컴포넌트 구성
  app/components/UploadMath.tsx
  app/globals.css
  components/common/LoadingModal.tsx
Labels: ✨ FEAT

#38 로고, 파비콘, 디폴트 이미지 변경
  app/layout.tsx
  components/common/RootHeader.tsx
  public/assets/kakao-login.png
  public/assets/logo.png
  public/assets/logo.svg
  public/assets/profile.png
  public/favicon.svg
Labels: 🎨 STYLE

#39 메인 페이지 - 최근 분석 결과 api 연동
  app/components/AnalysisResult.tsx
  app/components/UploadMath.tsx
  components/ui/listcard.tsx
  components/ui/skeleton.tsx
  next.config.ts
Labels: ✨ FEAT, 🎨 STYLE

#42 카카오 로그인 구현
  app/login/page.tsx
  app/success/page.tsx
  app/users/components/AnalysisCard.tsx
  app/users/page.tsx
  lib/authorizedFetch.ts
  lib/store/useUserStore.ts
  package-lock.json
  package.json
Labels: ✨ FEAT

#47 마이페이지 - 자녀 조회 api 연동
  app/users/components/AnalysisCard.tsx
  app/users/components/ChildCard.tsx
  app/users/page.tsx
Labels: ✨ FEAT, 🎨 STYLE

#53 메인, 결과 페이지 api 연동
  app/components/AnalysisResult.tsx
  app/components/UploadMath.tsx
  app/result/[logSolvedId]/page.tsx
  app/result/components/Problem.tsx
  app/result/components/Solve.tsx
  app/result/page.tsx
  components/common/BodyWrapper.tsx
  components/common/RootHeader.tsx
  components/ui/listcard.tsx
Labels: ✨ FEAT, 🎨 STYLE, 🐛 FIX

#58 마이페이지 - 자녀 등록/수정 API 변경 반영
  app/success/page.tsx
  app/users/components/ChildCard.tsx
  app/users/components/ChildForm.tsx
  app/users/page.tsx
Labels: ✨ FEAT, ♻️ REFACTOR

#63 이미지 분석 api 수정사항 반영
  app/components/AnalysisResult.tsx
  app/components/UploadMath.tsx
Labels: 🐛 FIX

#67 redirect uri 파라미터로 백엔드 전송
  app/login/page.tsx
Labels: ♻️ REFACTOR

#70 마이페이지 리팩토링
  app/users/components/AnalysisCard.tsx
  app/users/page.tsx
Labels: ✨ FEAT, ♻️ REFACTOR, 🐛 FIX

#79 사용자 비로그인 시 예외처리 케이스 추가
  app/globals.css
  app/page.tsx
  app/result/[logSolvedId]/page.tsx
  components/common/AuthModal.tsx
  hooks/useAuthRedirect.ts
  public/assets/lottie/lock.json
Labels: ✨ FEAT, ♻️ REFACTOR, 🎨 STYLE

#82 image loader 설정
  app/result/components/Problem.tsx
  next.config.ts
Labels: 🐛 FIX

#88 로그인/회원 관리 API 리팩토링
  app/components/AnalysisResult.tsx
  app/success/page.tsx
  app/users/components/LogoutButton.tsx
  app/users/components/WithdrawButton.tsx
  app/users/page.tsx
  stores/useUserStore.ts
Labels: ✨ FEAT, ♻️ REFACTOR

#90 로그아웃 시 selected child local storage 유지
  app/users/components/LogoutButton.tsx
Labels: ♻️ REFACTOR, 🐛 FIX

#92 자녀 프로필 이미지 수정 api 연동
  app/users/components/ChildForm.tsx
  app/users/edit/[id]/page.tsx
Labels: ✨ FEAT

#94 로그인/마이페이지 UI 수정
  app/login/page.tsx
  app/users/components/AddChildCard.tsx
  app/users/components/ChildCard.tsx
  app/users/components/ChildForm.tsx
  app/users/components/ui/ChildCardSkeleton.tsx
  app/users/page.tsx
  app/users/register-child/page.tsx
  components/common/ConfirmModal.tsx
Labels: 🎨 STYLE

#96 ESLint 경고 해결
  app/login/components/AnimatedCounter.tsx
  app/users/components/AnalysisCard.tsx
  app/users/edit/[id]/page.tsx
Labels: 🐛 FIX

#103 비로그인 상태에서 자녀 등록/수정 페이지 접근 제한 , 공통 로딩 컴포넌트 사용
  app/users/components/LogoutButton.tsx
  app/users/edit/[id]/page.tsx
  app/users/page.tsx
  app/users/register-child/page.tsx
Labels: ♻️ REFACTOR

#109 헤더 렌더링 및 자녀 선택 상태 오류 수정
  app/users/components/ChildCard.tsx
  components/common/BodyWrapper.tsx
  config/pagesConfig.ts
Labels: ♻️ REFACTOR, 🐛 FIX

#110 [RELEASE] 1.0.2 : 자녀 등록/수정 페이지 헤더 개선 및 상태 오류 수정
  app/users/components/ChildCard.tsx
  components/common/BodyWrapper.tsx
  config/pagesConfig.ts
Labels: 🏷️ RELEASE

#118 README 업데이트
  .github/images/cover.png
  .github/images/feat_01.png
  .github/images/feat_02.png
  README.md
Labels: 📝 DOCS

#119 [RELEASE] 1.0.4
  .github/images/cover.png
  .github/images/feat_01.png
  .github/images/feat_02.png
  README.md
Labels: 🏷️ RELEASE
